title: Fiix API Coding Examples
description: A hub for coding examples for the Fiix CMMS API.
theme: just-the-docs

url: https://just-the-docs.github.io

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo_ra_fiix.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Aux links for the upper right navigation
aux_links:
  Fiix Developer's Guide:
    - "https://fiixlabs.github.io/api-documentation/guide.html"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

